service: my-serverless-app
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: amalieiev-serverless

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"

plugins:
  - serverless-webpack

custom:
  webpack:
    keepOutputDirectory: true
    webpackConfig: webpack-config.js
    includeModules:
      forceExclude:
        - "@aws-sdk/client-dynamodb"
        - "@aws-sdk/lib-dynamodb"

functions:
  GetUsers:
    handler: src/http/get-users.handler
    events:
      - http:
          method: GET
          path: /v1/my-serverless-app/get-users
          cors: true
